### ISSUE TITLE
ERROR parse_bar: malformated line

### ISSUE THREAD

**Issue by Froloket64** [denisse-dev/dotfiles#12]
Hey, just copied your i3blocks config file into my ~/.config/i3blocks/ and refreshed i3 and in i3bar I got `(exit 1)` for `status_command`.

That's the terminal output of i3blocks command:
`ERROR parse_bar:162: malformated line: ROFI_TEXT=Menu:
ERROR main:70: Try 'i3blocks -h' for more information.`

Sorry if i did smth stupid, I'm just a newbie to i3.

**PS:** `rofi` is installed.

**Comment by Froloket64** [comment]
i3blocks with standart config runs normally.

**Comment by Froloket64** [comment]
Well, it's been around 11 days since I opened the issue and no one is here (not to blame anyone, really). I'm not sure if it's _correct_ to close the issue now, so I'll just leave it there. However, my problem can be even not the config's issue, cause I encounter such ones on many (all) configs of `i3blocks`.

Well, anyway, would be really glad if anyone helps, since I see other people also having problems with that "_malformating_" in `blocks`.

**Comment by p4t0k** [comment]
I know this is an old issue, but it can still be relevant for people like me who use the distribution package i3blocks from the Debian 11 repo which is of the buggy version 1.4.

I had this problem with disk-io, and my workaround is to run command the variable (LABEL in my case) before the actual command, like this:
 
`command=LABEL="I/O " $SCRIPT_DIR/disk-io`
